name: Run Selenium+Cucumber+TestNG Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: runnerLuis

    steps:
      - name: Kill orphan Chrome processes
        run: |
          pkill chrome || true

      - name: Install Chrome
        run: |
          apt-get update
          apt-get install -y wget gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable

      - name: Check Chrome version
        run: google-chrome --version

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      - name: Upload HTML Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-basic-report
          path: target/index.html

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
