name: Run Selenium+Cucumber+TestNG Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: runnerLuis

    container:
      image: selenium/standalone-chrome:latest
      options: --shm-size=2g

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Maven y Java ya vienen en la imagen de Selenium Standalone
      - name: Run tests with Maven
        run: mvn clean test

      # (Opcional) Subir reportes
      # - name: Upload Surefire Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: surefire-reports
      #     path: target/surefire-reports

      # - name: Upload Allure Results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-results
      #     path: target/allure-results
