name: Run Selenium+Cucumber+TestNG Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      # (Opcional) Subir reportes
      # - name: Upload Surefire Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: surefire-reports
      #     path: target/surefire-reports

      # - name: Upload Allure Results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-results
      #     path: target/allure-results
