name: Run Selenium+Cucumber+TestNG Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  test:
    name: Lanzar pruebas y generar reporte
    runs-on: runnerLuis
    steps:
      - name: Kill orphan Chrome processes
        run: |
          pkill chrome || true

      - name: Install Chrome
        run: |
          apt-get update
          apt-get install -y wget gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable

      - name: Check Chrome version
        run: google-chrome --version

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn clean test

      - name: Prepare report folder
        run: |
          mkdir -p report
          cp target/index.html report/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: report

  deploy:
    name: Publicar Reporte en GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
