name: Deploy Cucumber Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Run Selenium+Cucumber+TestNG Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/deploy-pages@v2
